### ISSUE TITLE
User API Epic

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/globalping#153]
This relies on the jsDelivr API and implementation which is up to Martin to decide. But I wanted to make a list of the features we will need to support:

- Full user dashboard as part of jsdelivr.com
- [x] Ability to adopt a probe. A user should be able to enter the IPs of the probes he controls to adopt them. I imagine this working like this: 1. Enter IP address of probe 2. Message asks the user to login where the probe is running and follow the logs output 3. The API sends a special command to that specific probe that prints a message to the user in the logs. It would contain a unique one-time code that would verify ownership 4. The user enters the code in the dashboard 5. The probe is now his
- [x] Remove probes 
- [x] Rename probes but limited to the user's point of view. Not public.
- [x] Show probe location, uptime, state and version. IP is safe to show too since the user owns the probes.
- [LATER] Ideally show number of processed tests per probe per day
- [x] Allow users to change probe city 
- Provide API key to interact with the Globalping API + ability to regenerate for security
- Add the limits system we describe in our readme. Specific numbers to be discussed.
- Integrate with Github Sponsors to associate jsDelivr users with sponsors and automatically upgrade and downgrade accounts and their API limits
- Add a credits system. https://github.com/jsdelivr/globalping/issues/53#issuecomment-1201663541 Each adopted probe would generate a certain amount of "credits" per day that can then be spent on running tests. Basically the user can get higher API limits without becoming a GH Sponsor if he owns lots of servers.
- [x] Tag system. Allow the user to set a limited amount of tags on adopted probes. Then he would be able to use the API to query them specifically. Something like `tag:u-jimaek-value` . Example use case: A company wants to use Globalping to run tests from their own specific locations and avoid all public probes. They would add them to the network and adopt them. They would then be shared by all of course. But they can also tag them to allow them to run their own tests only from their probes. e.g. a CDN running a probe in every POP to test their latency to the internet. 
~~- System tags. On top of the above we would need to have our own tags that users cant change but can use to query probes. Example: public-dns, regional-dns, datacenter. https://github.com/jsdelivr/globalping/issues/236~~
- Other?

Added value features:
- Monitor local internet stats. Allow the user to track his internet uptime, latency to key services, packet loss...
- Get notified when a probe goes down and up

**Comment by patrykcieszkowski** [comment]
Probe authentication wise - wouldn't it be easier to provide an API key in env variables during probe startup, rather than asking user to provide its IP address and lookup container stdout?

**Comment by jimaek** [comment]
I want to keep the probes read-only as much as possible, it makes the things easier. Also it feels a better UX like this for the people that are not that experienced with containers.

**Comment by MartinKolarik** [comment]
Notes:
 - We agreed that IPs will be used to identify probes. Once a probe is assigned to an account, it'll belong to that account even after reconnecting, as long as it has the same IP.
 - The IP ownership will expire after 30 days of being offline.
